language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
    - composer install -n
    - app/console doctrine:database:drop -e test --force
    - app/console doctrine:database:create -e test
    - app/console doctrine:schema:create -e test


script: phpunit -c app

