parameters:
#    sf_vlc_news.example.class: SfVlc\NewsBundle\Example

services:
#    sf_vlc_news.example:
#        class: %sf_vlc_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
