services:
    sfvlc.handy_test.user_factory:
        class: SfVlc\UserBundle\Factory\UserFactory
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: handy_tests.factory }