services:
    sfvlc.handy_test.user_factory:
        class: SfVlc\UserBundle\Factory\UserFactory
        arguments: ["@fos_user.user_manager"]
        tags:
            - { name: handy_tests.factory }